### PR TITLE
docs: provide a complete pnpm config instructions

### PR DESCRIPTION
**Pull request by lirantal**
## Changes

This change updates the pnpm configuration directives to provide a fully working reference to a configuration file that works for the plugin on VS Code

### CODE REVIEW

**Comment by Princesseuh** [comment]
Hmm, since there's a fully working config for VS Code in the section below where you added this, isn't this a bit of a duplicate?

**Comment by lirantal** [comment]
I don't know if it's a "full example" because it doesn't mention the `pluginSearchDirs` which I found I need to have in order to work. I'm happy to change that part instead.

**Comment by Princesseuh** [comment]
> I don't know if it's a "full example" because it doesn't mention the `pluginSearchDirs` which I found I need to have in order to work. I'm happy to change that part instead.

`pluginSearchDirs` and manually setting the plugins in `plugins` should have the same behaviour! I actually kinda point toward using `plugins` explicitly instead of relying on Prettier's auto-loading on purpose, as it is kinda buggy at times and doesn't work well with plugins that needs a specific plugin order (such as the very popular `prettier-plugin-tailwindcss`

I'd confirm on your side if that config doesn't work, because as far as I know (and test on my end), it should cover all use cases!

**Comment by lirantal** [comment]
Ahh, I can try them both and see if it works :-)
I'll report back

**Comment by lirantal** [comment]
I confirm this is working indeed:

```
{
  "overrides": [
    {
      "files": "**/*.astro",
      "options": { "parser": "astro" }
    }
  ],
  "plugins": ["./node_modules/prettier-plugin-astro"]
}
```

Thank you @Princesseuh

**Pull request closed without merging**
