### PR TITLE
Do not delete line breaks and indentation of lines in class attribute

### PR DESCRIPTION
**Pull request by artemst**
See https://github.com/withastro/prettier-plugin-astro/issues/368

### CODE REVIEW

**Comment by Princesseuh** [comment]
The logic for printing class names in Prettier itself seems to be quite simple: https://github.com/prettier/prettier/blob/e974e309c3207ddcf8d84317313acbb6984566f7/src/language-html/embed/class-names.js, any chance we could copy that?

**Comment by artemst** [comment]
Ah, I was confused by some messages in https://github.com/prettier/prettier/issues/10918 and thought that final decision was to preserve new lines. Prettier do format all classes in one line in raw html files.

But prettier-plugin-svelte decided to preserve new lines: https://github.com/sveltejs/prettier-plugin-svelte/blob/master/src/print/index.ts#L170C32-L170C32
It is really frustrating to see all this Tailwind classes reformatted in one long line. Any chance that astro can adopt  this behavior? May be with additional option then?

**Comment by Princesseuh** [comment]
Hmm, okay. That seems fine to me, especially if Svelte is doing the same thing. Any major differences between your implementation and theirs?

**Comment by artemst** [comment]
I see two differences: 
1. They keep leading indentation in first line of classes. I think it's unnecessary, leading spaces in the first line doesn't add any readability. So I keep indentations only for following lines.
2. I realized that I split lines by '\r\n' or '\n', but join them by '\n' only. Svelte plugin keeps '\r\n' as line breaker. I saw in the source code that astro plugin forces '\n' line breaks for some code, like sass. Do we need to keep '\r\n' in astro files?

**Comment by Princesseuh** [comment]
We don't *need* to, I assume maybe it would be better, but as you've said there's numerous places where we always use `\n` and I've never heard anyone complain on Windows, so maybe it's not a problem. If it turns out to be, we can fix it in a separate dedicated PR that fixes all instances of it.

Thank you very much for this PR!

**Comment by artemst** [comment]
Thank you for your help!

**Pull request merged**
